#!/bin/bash

# shellcheck disable=SC1090

BUILD_PATH="$(dirname "$0")"
COMMAND=$(basename "$0")

. "${BUILD_PATH}/config/globals.sh"

OPTION=$1
shift

declare -a options=(
	"build"
	"clean"
	"countlines"
	"help"
	"regenerate"
	"stationTV"
	"ubuntu"
	)

MATCHES=()
if [[ a"$OPTION"a == "aa" ]]; then
	OPTION="build"
fi

for element in "${options[@]}"; do
	if [[ "$element" == "$OPTION"* ]]; then
		MATCHES+=(${element})
	fi
done

if [[ "${#MATCHES[@]}" -eq 0 ]]; then
	echo "${COMMAND}: unknown command '${OPTION}'"
	MATCHES+=("help")
fi

if [[ "${#MATCHES[@]}" -eq 1 ]]; then
	OPTION="${MATCHES[0]}"
fi

if [[ "${#MATCHES[@]}" -gt 1 ]]; then
	echo "${COMMAND}: command '${OPTION}' is ambiguous:"
	echo "   " "${MATCHES[@]}"
	exit
fi

case "$OPTION" in
	build)
		. "$BUILD_PATH"/scripts/build-build "$@"
		;;
	clean)
		. "$BUILD_PATH"/scripts/build-clean "$@"
		;;
	countlines)
		. "$BUILD_PATH"/scripts/build-countlines "$@"
		;;
	regenerate)
		. "$BUILD_PATH"/scripts/build-regenerate "$@"
		;;
	stationTV)
		cd samples/stationTV || exit
		./stationTV
		cd ../.. || exit
		;;
	ubuntu)
		. "$BUILD_PATH"/scripts/build-ubuntu "$@"
		;;
	*)
		echo "Build"
		echo
		echo "basic commands:"
		echo
		echo " build         build projects (efault)"
		echo " clean         clean projects"
		echo " countlines    count all project lines"
		echo " help          display this help and exit"
		echo " regenerate    regenerate cmake projects and build"
		echo " stationTV     launch stationTV"
		echo " ubuntu        Check Ubuntu development packages"
		echo

		exit 1
		;;
esac

