#!/bin/sh

if [ "$BUILD_TYPE" = "Debug" ]; then
	mkdir -p b/d/libawui
	cd b/d/libawui || exit
else
	mkdir -p b/r/libawui
	cd b/r/libawui || exit
fi

($COMMAND_BUILD)
cd ../../.. || exit

cd samples || exit
($COMMAND_BUILD)
cd .. || exit

